domain_path: E:\HardSoftCodesign\Hardsoftcodesign\RAPID\motorDriver\export\motorDriver\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
