# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/HardSoftCodesign/Hardsoftcodesign/RAPID/RAPID.srcs/sources_1/bd/top/ip/top_rst_ps7_0_100M_1/top_rst_ps7_0_100M_1.xci
# IP: The module: 'top_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HardSoftCodesign/Hardsoftcodesign/RAPID/RAPID.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_1/top_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/HardSoftCodesign/Hardsoftcodesign/RAPID/RAPID.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_1/top_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/HardSoftCodesign/Hardsoftcodesign/RAPID/RAPID.srcs/sources_1/bd/top/ip/top_rst_ps7_0_100M_1/top_rst_ps7_0_100M_1.xci
# IP: The module: 'top_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/HardSoftCodesign/Hardsoftcodesign/RAPID/RAPID.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_1/top_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/HardSoftCodesign/Hardsoftcodesign/RAPID/RAPID.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_1/top_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
