# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/RAPID.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0_1/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_Spindle_0_0/top_Spindle_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Spindle_0_0 || ORIG_REF_NAME==top_Spindle_0_0} -quiet] -quiet

# IP: bd/top/ip/top_stepperDriver_0_0_1/top_stepperDriver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_stepperDriver_0_0 || ORIG_REF_NAME==top_stepperDriver_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_gpio_0_1/top_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_gpio_0_1 || ORIG_REF_NAME==top_axi_gpio_0_1} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_1/top_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_1 || ORIG_REF_NAME==top_xlslice_0_1} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_2/top_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_2 || ORIG_REF_NAME==top_xlslice_0_2} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_3/top_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_3 || ORIG_REF_NAME==top_xlslice_0_3} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_4/top_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_4 || ORIG_REF_NAME==top_xlslice_0_4} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_5/top_xlslice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_5 || ORIG_REF_NAME==top_xlslice_0_5} -quiet] -quiet

# IP: bd/top/ip/top_xlslice_0_6/top_xlslice_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlslice_0_6 || ORIG_REF_NAME==top_xlslice_0_6} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_100M_1/top_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_100M_1 || ORIG_REF_NAME==top_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/top/ip/top_axi_smc_1/top_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_smc_1 || ORIG_REF_NAME==top_axi_smc_1} -quiet] -quiet

# XDC: c:/Users/mbracker/Documents/RAPID/RAPID/RAPID/RAPID.gen/sources_1/bd/top/top_ooc.xdc
