set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_baudoutn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_ctsn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_dcdn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_ddis]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_dsrn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_dtrn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_out1n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_out2n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_ri]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rtsn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxrdyn]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txrdyn]
set_property IOSTANDARD LVCMOS33 [get_ports phA1]
set_property IOSTANDARD LVCMOS33 [get_ports phA2]
set_property IOSTANDARD LVCMOS33 [get_ports phB1]
set_property IOSTANDARD LVCMOS33 [get_ports phB2]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN V17 [get_ports phA1]
set_property PACKAGE_PIN V18 [get_ports phA2]
set_property PACKAGE_PIN T16 [get_ports phB1]
set_property PACKAGE_PIN R17 [get_ports phB2]


set_property PACKAGE_PIN M20 [get_ports kill_0]
set_property IOSTANDARD LVCMOS33 [get_ports kill_0]

set_property IOSTANDARD LVCMOS33 [get_ports En_Spindle]
set_property PACKAGE_PIN R16 [get_ports En_Spindle]

set_property PACKAGE_PIN T14 [get_ports INHA_0]
set_property PACKAGE_PIN V13 [get_ports INLB_0]
set_property IOSTANDARD LVCMOS33 [get_ports INHA_0]
set_property IOSTANDARD LVCMOS33 [get_ports INHB_0]
set_property IOSTANDARD LVCMOS33 [get_ports INLA_0]
set_property IOSTANDARD LVCMOS33 [get_ports INLB_0]
set_property IOSTANDARD LVCMOS33 [get_ports INLC_0]
set_property DRIVE 12 [get_ports INLC_0]
set_property SLEW SLOW [get_ports INLC_0]
set_property PACKAGE_PIN U12 [get_ports INLA_0]
set_property PACKAGE_PIN U13 [get_ports INHB_0]
set_property PACKAGE_PIN T15 [get_ports INLC_0]
set_property PACKAGE_PIN V15 [get_ports INHC_0]
set_property IOSTANDARD LVCMOS33 [get_ports INHC_0]

set_property SLEW SLOW [get_ports INHC_0]
set_property SLEW SLOW [get_ports En_Spindle]
set_property SLEW SLOW [get_ports INHA_0]
set_property SLEW SLOW [get_ports INHB_0]
set_property SLEW SLOW [get_ports INLA_0]
set_property SLEW SLOW [get_ports INLB_0]


